// Hostinger publisher. On Hostinger Cloud/Business hosting the platform app cannot be the thing that
// serves <name>.nsd.sg: every subdomain is its own LiteSpeed vhost with a document root on disk.
// So this module turns the DB's picture of a site into files LiteSpeed will serve:
//
//   TENANT_ROOT/<label>/            <- document root of <label>.nsd.sg (created once via Hostinger API)
//       .htaccess                   <- no indexes, no CGI/PHP, no dotfiles, custom 404, security headers
//       index.html ...              <- copy of the current release, badge injected into every HTML file
//
// Every state change (deploy, rollback, suspend, branding, delete, plan change) calls syncSite(), which
// rebuilds the directory atomically: write <label>.new, swap it in with rename, remove the old one.
// The release directories under DATA_DIR stay pristine and remain the source of truth for versions/rollback.
//
// Same-process serving (src/serve/tenant.js) still works for local dev and the VPS deploy kit; on Hostinger
// tenant hosts never reach the app, so this file is the enforcement layer instead.
import fs from 'node:fs';
import path from 'node:path';
import { config } from '../config.js';
import { getDb } from '../db/index.js';
import { nowIso } from '../lib/ids.js';
import { esc } from '../lib/html.js';
import { extensionOf, HTML_EXTENSIONS } from '../lib/mime.js';
import { injectBranding } from '../serve/branding.js';
import { injectSocial } from '../serve/social.js';
import { platformUrl, publicUrlForSubdomain } from '../config.js';
import { entitlementsFor } from '../services/plans.js';
import { releaseDir } from '../storage/releases.js';

export class PublishError extends Error {}

const LABEL_RE = /^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])$/;
// Shared subdomain for anonymous "try it" previews (services/tryit.js). Never a site; excluded from orphan checks.
export const TRY_LABEL = 'try';
const MAX_HTML_INJECT_BYTES = 5 * 1024 * 1024;

export function isEnabled() {
  return !!config.hostinger.tenantRoot;
}

function tenantRoot() {
  if (!config.hostinger.tenantRoot) throw new PublishError('TENANT_ROOT is not configured');
  return config.hostinger.tenantRoot;
}

export function tenantDir(label) {
  if (!LABEL_RE.test(label)) throw new PublishError('bad label');
  return path.join(tenantRoot(), label);
}

// ---- Hostinger API -------------------------------------------------------------------------------

async function api(method, p, body) {
  const { apiToken, apiBase } = config.hostinger;
  if (!apiToken) return { skipped: true };
  const res = await fetch(`${apiBase}${p}`, {
    method,
    headers: { Authorization: `Bearer ${apiToken}`, 'Content-Type': 'application/json', Accept: 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(20_000),
  });
  const text = await res.text();
  let json;
  try { json = JSON.parse(text); } catch { json = { raw: text }; }
  if (!res.ok) throw new PublishError(`Hostinger API ${method} ${p} -> ${res.status}: ${(json.message ?? text).slice(0, 300)}`);
  return json;
}

const subdomainsPath = () => `/api/hosting/v1/accounts/${config.hostinger.username}/websites/${config.baseDomain}/subdomains`;

export async function listHostingSubdomains() {
  const r = await api('GET', subdomainsPath());
  return Array.isArray(r) ? r : (r.data ?? []);
}

/** Ask Hostinger to create <label>.<baseDomain> pointing at TENANT_ROOT/<label>. Idempotent. */
export async function provisionSubdomain(label) {
  const dir = tenantDir(label);
  fs.mkdirSync(dir, { recursive: true, mode: 0o755 });
  if (!config.hostinger.apiToken) return { provisioned: false, reason: 'no API token (local mode)' };
  const existing = await listHostingSubdomains();
  if (existing.some((s) => s.subdomain === label || s.domain === `${label}.${config.baseDomain}`)) return { provisioned: true, existed: true };
  // `directory` is relative to the website root (public_html).
  const rel = path.relative(config.hostinger.publicHtml, dir).split(path.sep).join('/');
  await api('POST', subdomainsPath(), { subdomain: label, directory: rel });
  return { provisioned: true, existed: false };
}

export async function deprovisionSubdomain(label) {
  const dir = tenantDir(label);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.rmSync(`${dir}.new`, { recursive: true, force: true });
  fs.rmSync(`${dir}.old`, { recursive: true, force: true });
  if (!config.hostinger.apiToken) return { deprovisioned: false, reason: 'no API token (local mode)' };
  try {
    await api('DELETE', `${subdomainsPath()}/${label}`);
  } catch (e) {
    if (!/404/.test(e.message)) throw e;
  }
  return { deprovisioned: true };
}

// ---- Document root builder ------------------------------------------------------------------------

export function htaccess({ has404, errorDoc = '', extra = [] }) {
  return [
    '# Generated by NSD.SG - do not edit; it is rewritten on every publish.',
    'Options -Indexes -ExecCGI -Includes',
    'DirectoryIndex index.html index.htm',
    'ServerSignature Off',
    '',
    '# Static only: nothing executes here.',
    '<FilesMatch "\\.(php|php[0-9]|phtml|phar|cgi|pl|py|rb|sh|asp|aspx|jsp)$">',
    '  Require all denied',
    '</FilesMatch>',
    '<IfModule mod_php.c>',
    '  php_flag engine off',
    '</IfModule>',
    '',
    '# Dotfiles are never served.',
    '<FilesMatch "^\\.">',
    '  Require all denied',
    '</FilesMatch>',
    '',
    '<IfModule mod_headers.c>',
    '  Header always set X-Content-Type-Options "nosniff"',
    '  Header always set Referrer-Policy "strict-origin-when-cross-origin"',
    '  Header always set X-Powered-By "NSD.SG"',
    '  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=()"',
    '</IfModule>',
    '',
    '<IfModule mod_rewrite.c>',
    '  RewriteEngine On',
    '  # Clean URLs: /about -> /about.html when that file exists.',
    '  RewriteCond %{REQUEST_FILENAME} !-f',
    '  RewriteCond %{REQUEST_FILENAME} !-d',
    '  RewriteCond %{REQUEST_FILENAME}.html -f',
    '  RewriteRule ^(.+?)/?$ $1.html [L]',
    '</IfModule>',
    '',
    ...extra,
    errorDoc ? `ErrorDocument 404 ${errorDoc}` : has404 ? 'ErrorDocument 404 /404.html' : 'ErrorDocument 404 /_nsd-404.html',
    '',
  ].join('\n');
}

function page(title, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${esc(title)}</title>
<style>body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#0f1014;color:#e8e8ec;display:grid;place-items:center;min-height:100vh}
main{max-width:520px;padding:2.5rem;text-align:center}h1{font-size:1.5rem;margin:0 0 .5rem}p{color:#a6a7b2;line-height:1.55}a{color:#a78bfa}
.mark{display:inline-block;font-weight:700;letter-spacing:.06em;color:#fff;margin-bottom:1.5rem}.mark b{color:#a78bfa}</style></head>
<body><main><div class="mark">NSD<b>.SG</b></div>${body}</main></body></html>`;
}

const PAGES = {
  empty: (label) => page('Coming soon', `<h1>Coming soon.</h1><p><strong>${esc(label)}.${esc(config.baseDomain)}</strong> belongs to someone, but there is no page on it yet.</p>`),
  suspended: () => page('Site unavailable', `<h1>This site is unavailable.</h1><p>NSD.SG has switched it off. If it is yours, log in to <a href="${esc(config.publicScheme)}://${esc(config.platformHosts[0])}/">NSD.SG</a> to see why.</p>`),
  notFoundFile: () => page('Page not found', `<h1>Page not found.</h1><p>There is no page with that name on this site. Check the link and try again.</p>`),
};

function brandingRemovedFor(site, owner) {
  if (site.branding_removed) return true;
  const ent = entitlementsFor(owner);
  return ent.brandingRemoved && !ent.expired;
}

/** Copy a release tree into `dst`, injecting the badge into HTML files. Returns file count. */
function materialise(srcRoot, dstRoot, { badge, social = null }) {
  let count = 0;
  (function walk(src, dst, rel = '') {
    for (const ent of fs.readdirSync(src, { withFileTypes: true })) {
      if (ent.name.startsWith('.')) continue; // never publish dotfiles (also blocks .htaccess overrides)
      const s = path.join(src, ent.name);
      const d = path.join(dst, ent.name);
      if (ent.isDirectory()) {
        fs.mkdirSync(d, { recursive: true, mode: 0o755 });
        walk(s, d, `${rel}${ent.name}/`);
      } else if (ent.isFile()) {
        if ((badge || social) && HTML_EXTENSIONS.has(extensionOf(ent.name))) {
          let buf = fs.readFileSync(s);
          if (buf.length <= MAX_HTML_INJECT_BYTES) {
            if (badge) buf = injectBranding(buf);
            if (social) buf = injectSocial(buf, { ...social, url: `${social.base}/${ent.name === 'index.html' ? rel : `${rel}${ent.name}`}` });
          }
          fs.writeFileSync(d, buf, { mode: 0o644 });
        } else {
          fs.copyFileSync(s, d);
          fs.chmodSync(d, 0o644);
        }
        count += 1;
      }
      // symlinks and anything else are dropped silently
    }
  })(srcRoot, dstRoot);
  return count;
}

/** Replace TENANT_ROOT/<label> with the contents of `build` in one rename. */
function swapIn(label, build) {
  const live = tenantDir(label);
  const old = `${live}.old`;
  fs.rmSync(old, { recursive: true, force: true });
  if (fs.existsSync(live)) fs.renameSync(live, old);
  fs.renameSync(build, live);
  fs.rmSync(old, { recursive: true, force: true });
}

/**
 * Bring the served directory of one site in line with the database.
 * Never throws for filesystem problems: the result is recorded on the site row and returned.
 */
export function syncSite(siteId) {
  if (!isEnabled()) return { skipped: true };
  const db = getDb();
  const site = db.prepare('SELECT * FROM sites WHERE id = ?').get(siteId);
  if (!site) return { skipped: true, reason: 'no such site' };
  const owner = db.prepare('SELECT * FROM users WHERE id = ?').get(site.user_id);
  const label = site.subdomain;
  if (site.status === 'deleted' || !LABEL_RE.test(label)) return { skipped: true, reason: 'deleted' };

  const build = `${tenantDir(label)}.new`;
  try {
    fs.rmSync(build, { recursive: true, force: true });
    fs.mkdirSync(build, { recursive: true, mode: 0o755 });
    let mode;
    let files = 0;
    const dark = site.status === 'suspended' || !owner || owner.status !== 'active';
    if (dark) {
      mode = 'suspended';
      fs.writeFileSync(path.join(build, 'index.html'), PAGES.suspended());
      // Every path on a suspended site shows the notice (LiteSpeed has no clean 451 for static vhosts).
      fs.writeFileSync(path.join(build, '.htaccess'), htaccess({ has404: false }) + '\n<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteCond %{REQUEST_URI} !^/index\\.html$\nRewriteRule ^ /index.html [L]\n</IfModule>\n');
    } else if (!site.current_release_id) {
      mode = 'empty';
      fs.writeFileSync(path.join(build, 'index.html'), PAGES.empty(label));
      fs.writeFileSync(path.join(build, '.htaccess'), htaccess({ has404: false }));
    } else {
      mode = 'live';
      const src = releaseDir(site.id, site.current_release_id);
      if (!fs.existsSync(src)) throw new PublishError(`release directory missing: ${site.current_release_id}`);
      const badge = !brandingRemovedFor(site, owner);
      files = materialise(src, build, { badge, social: { base: publicUrlForSubdomain(label), siteName: `${label}.${config.baseDomain}`, image: platformUrl('/assets/social-site.png') } });
      const has404 = fs.existsSync(path.join(build, '404.html'));
      fs.writeFileSync(path.join(build, '.htaccess'), htaccess({ has404 }));
    }
    fs.writeFileSync(path.join(build, '_nsd-404.html'), PAGES.notFoundFile());
    swapIn(label, build);
    // hosting_state tracks subdomain provisioning (pending -> ready); a successful sync only clears a previous error.
    db.prepare("UPDATE sites SET hosting_synced_at = ?, hosting_error = '', hosting_state = CASE WHEN hosting_state = 'error' THEN 'pending' ELSE hosting_state END WHERE id = ?").run(nowIso(), siteId);
    return { ok: true, mode, files };
  } catch (e) {
    fs.rmSync(build, { recursive: true, force: true });
    const msg = String(e.message).slice(0, 500);
    db.prepare("UPDATE sites SET hosting_state = 'error', hosting_error = ? WHERE id = ?").run(msg, siteId);
    return { ok: false, error: msg };
  }
}

/** Resync every non-deleted site of one user (plan/status changes affect badge and availability). */
export function syncUserSites(userId) {
  if (!isEnabled()) return [];
  const rows = getDb().prepare("SELECT id FROM sites WHERE user_id = ? AND status != 'deleted'").all(userId);
  return rows.map((r) => ({ id: r.id, ...syncSite(r.id) }));
}

/** Resync everything (cron / CLI). Also provisions subdomains that are still pending. */
export async function syncAll() {
  if (!isEnabled()) return { skipped: true };
  const db = getDb();
  const out = { synced: 0, errors: 0, provisioned: 0 };
  for (const s of db.prepare("SELECT id, subdomain, hosting_state FROM sites WHERE status != 'deleted'").all()) {
    if (s.hosting_state === 'pending' || s.hosting_state === 'error') {
      try {
        await provisionSubdomain(s.subdomain);
        out.provisioned += 1;
      } catch (e) {
        db.prepare("UPDATE sites SET hosting_state = 'error', hosting_error = ? WHERE id = ?").run(String(e.message).slice(0, 500), s.id);
      }
    }
    const r = syncSite(s.id);
    if (r.ok) out.synced += 1; else if (r.ok === false) out.errors += 1;
    if (r.ok && (s.hosting_state === 'pending' || s.hosting_state === 'error') && config.hostinger.apiToken) {
      db.prepare("UPDATE sites SET hosting_state = 'ready', hosting_error = '' WHERE id = ?").run(s.id);
    }
  }
  return out;
}

/** Remove orphan tenant directories that no live site owns (safety net after crashes). */
export function listOrphanDirs() {
  if (!isEnabled() || !fs.existsSync(tenantRoot())) return [];
  const live = new Set(getDb().prepare("SELECT subdomain FROM sites WHERE status != 'deleted'").all().map((r) => r.subdomain));
  live.add(TRY_LABEL);
  return fs.readdirSync(tenantRoot()).filter((d) => !live.has(d.replace(/\.(new|old)$/, '')));
}

/** Delete one orphan directory (only names returned by listOrphanDirs are accepted). */
export function removeOrphanDir(name) {
  if (!listOrphanDirs().includes(name)) return false;
  fs.rmSync(path.join(tenantRoot(), name), { recursive: true, force: true });
  return true;
}

/** Key names (never values) found in DATA_DIR/.env, or null when the file is absent. */
export function envFileKeys() {
  const file = path.join(config.dataDir, '.env');
  if (!fs.existsSync(file)) return null;
  return fs.readFileSync(file, 'utf8').split('\n').map((l) => l.trim()).filter((l) => l && !l.startsWith('#') && l.includes('=')).map((l) => l.slice(0, l.indexOf('=')).trim());
}
